const arTranslations = {
  joinMeeting: "انضم إلى اجتماع",
  hostMeeting: "استضافة اجتماع",
  startNewMeeting: "بدء اجتماع جديد",
  enterMeetingCode: "أدخل رمز الاجتماع",
  welcome: "مرحباً بك في Doodle Meet",
  newMeeting: "اجتماع جديد",
  createMeeting: "إنشاء اجتماع جديد ودعوة الآخرين",
  joinMeetingTitle: "انضم إلى اجتماع",
  joinMeetingDesc: "انضم إلى اجتماع باستخدام الرمز",
  logout: "تسجيل خروج",
  profileSettings: "إعدادات الملف الشخصي",
  manageAccount: "إدارة إعدادات وتفضيلات حسابك",
  // Profile Page
  personalInfo: "المعلومات الشخصية",
  fullName: "الاسم الكامل",
  email: "البريد الإلكتروني",
  phone: "رقم الهاتف",
  meetingPreferences: "تفضيلات الاجتماع",
  muteMicJoin: "كتم الميكروفون عند الانضمام",
  turnOffCamJoin: "إيقاف الكاميرا عند الانضمام",
  highQualityVideo: "استخدام فيديو عالي الجودة",
  languageSettings: "إعدادات اللغة",
  preferredLanguage: "اللغة المفضلة",
  saveChanges: "حفظ التغييرات",
  cancel: "إلغاء",
};
