const enTranslations = {
  joinMeeting: "Join Meeting",
  hostMeeting: "Host Meeting",
  startNewMeeting: "Start New Meeting",
  enterMeetingCode: "Enter meeting code",
  welcome: "Welcome to Doodle Meet",
  newMeeting: "New Meeting",
  createMeeting: "Create a new meeting and invite others",
  joinMeetingTitle: "Join Meeting",
  joinMeetingDesc: "Join a meeting with a code",
  logout: "Log out",
  profileSettings: "Profile Settings",
  manageAccount: "Manage your account settings and preferences",
  // Profile Page
  personalInfo: "Personal Information",
  fullName: "Full Name",
  email: "Email",
  phone: "Phone Number",
  meetingPreferences: "Meeting Preferences",
  muteMicJoin: "Mute microphone when joining",
  turnOffCamJoin: "Turn off camera when joining",
  highQualityVideo: "Use high quality video",
  languageSettings: "Language Settings",
  preferredLanguage: "Preferred Language",
  saveChanges: "Save Changes",
  cancel: "Cancel",
};
