const esTranslations = {
  joinMeeting: "Unirse a la reunión",
  hostMeeting: "Organizar reunión",
  startNewMeeting: "Iniciar nueva reunión",
  enterMeetingCode: "Ingrese el código de la reunión",
  welcome: "Bienvenido a Doodle Meet",
  newMeeting: "Nueva reunión",
  createMeeting: "Crear una nueva reunión e invitar a otros",
  joinMeetingTitle: "Unirse a la reunión",
  joinMeetingDesc: "Unirse a una reunión con un código",
  logout: "Cerrar sesión",
  profileSettings: "Configuración del perfil",
  manageAccount: "Administre la configuración y preferencias de su cuenta",
  // Profile Page
  personalInfo: "Información Personal",
  fullName: "Nombre Completo",
  email: "Correo Electrónico",
  phone: "Número de Teléfono",
  meetingPreferences: "Preferencias de Reunión",
  muteMicJoin: "Silenciar micrófono al unirse",
  turnOffCamJoin: "Apagar cámara al unirse",
  highQualityVideo: "Usar video de alta calidad",
  languageSettings: "Configuración de Idioma",
  preferredLanguage: "Idioma Preferido",
  saveChanges: "Guardar Cambios",
  cancel: "Cancelar",
};
